### ISSUE TITLE
Ошибка: Ошибочная структура подсистем

### ISSUE THREAD

**Issue by Kyrales** [bia-technologies/autodocgen#2]
ОШИБКА - Генерация документации завершилась ошибкой: d:\1C\Kyporos_ci\src\cf\BusinessProcesses\Задание\Ext\ManagerModule.bsl: ошибочная структура подсистем

Команда:
autodocgen generate -c v8config.json -f html d:\1C\Kyporos_ci

Файл:
```json
{
    "GLOBAL": {
        "КаталогИсходныхФайлов": "src//cf",
        "КаталогКонфигурации": "src//cf"
    },
    "AutodocGen":{
        "НастройкиHTML": {
            "ПутьКШаблонам": "",
            "КаталогПубликации": "./markdown"
        }
  }
}
```

**Comment by theshadowco** [comment]
Вопрос не сформулирован, но попробую догадаться: почему выдает ошибку? 
Сообщение об ошибке говорит, что структура подсистем не соответствует ожидаемой, ожидаемая описана в документации.

**Comment by Kyrales** [comment]
@theshadowco cсылаюсь на структуру полученную из gitsync

**Comment by theshadowco** [comment]
Посмотрите, как у вас подсистемы в конфигурации сконструированы и то, чего ждёт скрипт.

**Comment by theshadowco** [comment]
А он ждёт так, как написано в доеументации
